version: '3.1'

services:

  wordpress:
    image: "vuln-wordpress:4.7.0"
    build:
      context: ./4.7.0/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - fix_wordpress_permissions
  fix_wordpress_permissions:
    image: "vuln-wordpress:4.7.0"
    build:
      context: ./4.7.0/
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    command: chown -R www-data:www-data /var/www/html/
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
          - "81:80"
      expose:
          - 81
      environment:
          PMA_HOST: db
      depends_on:
        - db

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: $PWD/wordpress-data
      o: bind
  db:
